//   /    Context:                     https://ctx.ist
// ,'`./    do you remember?
// `.,'\
//   \    Copyright 2026-present Context contributors.
//                 SPDX-License-Identifier: Apache-2.0

package loop

import (
	"fmt"
	"path/filepath"
)

// generateLoopScript creates a bash script for running a Ralph loop.
//
// The generated script runs the specified AI tool repeatedly with the
// same prompt file until a completion signal is detected in the output.
//
// Parameters:
//   - promptFile: Path to the prompt file (converted to absolute path)
//   - tool: AI tool to use - "claude", "aider", or "generic"
//   - maxIterations: Maximum iterations before stopping (0 for unlimited)
//   - completionMsg: String to detect in output that signals completion
//
// Returns:
//   - string: Complete bash script content ready to write to file
func generateLoopScript(
	promptFile, tool string, maxIterations int, completionMsg string,
) string {
	// Get the absolute path for the prompt file
	absPrompt, _ := filepath.Abs(promptFile)

	var aiCommand string
	switch tool {
	case "claude":
		aiCommand = fmt.Sprintf(`claude --print "$(cat %s)"`, absPrompt)
	case "aider":
		aiCommand = fmt.Sprintf(`aider --message-file %s`, absPrompt)
	case "generic":
		aiCommand = fmt.Sprintf(`# Replace with your AI CLI command
    cat %s | your-ai-cli`, absPrompt)
	}

	maxIterCheck := ""
	if maxIterations > 0 {
		maxIterCheck = fmt.Sprintf(`
    # Check iteration limit
    if [ $ITERATION -ge %d ]; then
        echo "Reached maximum iterations (%d)"
        break
    fi`, maxIterations, maxIterations)
	}

	script := fmt.Sprintf(`#!/bin/bash
#
# Ralph Loop Script
# Generated by: ctx loop
#
# This script runs an AI assistant in a loop until completion.
# The AI works on the same prompt file repeatedly, building on
# previous work visible in files and git history.
#

set -e

PROMPT_FILE="%s"
COMPLETION_SIGNAL="%s"
ITERATION=0

echo "Starting Ralph Loop"
echo "==================="
echo "Prompt: $PROMPT_FILE"
echo "Completion signal: $COMPLETION_SIGNAL"
echo ""

# Ensure prompt file exists
if [ ! -f "$PROMPT_FILE" ]; then
    echo "Error: Prompt file not found: $PROMPT_FILE"
    exit 1
fi

while true; do
    ITERATION=$((ITERATION + 1))
    echo ""
    echo "=== Iteration $ITERATION ==="
    echo ""
%s
    # Run the AI tool
    OUTPUT=$(%s 2>&1) || true

    echo "$OUTPUT"

    # Check for completion signal
    if echo "$OUTPUT" | grep -q "$COMPLETION_SIGNAL"; then
        echo ""
        echo "=== Loop Complete ==="
        echo "Detected completion signal: $COMPLETION_SIGNAL"
        echo "Total iterations: $ITERATION"
        break
    fi

    # Small delay to prevent runaway loops
    sleep 1
done
`, absPrompt, completionMsg, maxIterCheck, aiCommand)

	return script
}
